---
services:
  webtop:
    image: digitalproteomes/protter
    build: .
    container_name: guacd
    ports:
      - 3000:3000
      - 8181:81
    volumes:
      - /home/pepatric/Software/Sources/protter_docker/Protter:/Protter
    restart: unless-stopped
    command: /Protter/start.sh
